<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJSvK478\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJSvK478/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJSvK478.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJSvK478\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJSvK478\App_KernelDevDebugContainer([
    'container.build_hash' => 'JSvK478',
    'container.build_id' => '0929a5ee',
    'container.build_time' => 1648213170,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJSvK478');
